# Generated by Django 5.2.14 on 2026-05-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_user_column_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='numchild',
            field=models.PositiveIntegerField(db_column='numchild', default=0),
        ),
        migrations.RenameField(
            model_name='item',
            old_name='numchild',
            new_name='_deprecated_numchild',
        ),
        migrations.AlterField(
            model_name='item',
            name='numchild_folder',
            field=models.PositiveIntegerField(db_column='numchild_folder', default=0),
        ),
        migrations.RenameField(
            model_name='item',
            old_name='numchild_folder',
            new_name='_deprecated_numchild_folder',
        ),
        migrations.AlterField(
            model_name='item',
            name='upload_state',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('duplicating', 'Duplicating'), ('analyzing', 'Analyzing'), ('suspicious', 'Suspicious'), ('file_too_large_to_analyze', 'File too large to analyze'), ('ready', 'Ready')], max_length=25, null=True),
        ),
    ]
