# Generated by Django 5.2.14 on 2026-06-17
# B1-1 (item content-object metadata) + A2-1 (AuditEvent + audit.record service).
# Note: this migration is intentionally scoped to those two stories. Unrelated
# pre-existing model/migration drift on this branch (numchild rename,
# upload_state and user.language AlterField) is left untouched (status quo).

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_user_column_preferences"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="date and time at which the event was recorded",
                        verbose_name="recorded on",
                    ),
                ),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("system", "System"),
                            ("api", "API key"),
                            ("anonymous", "Anonymous"),
                        ],
                        default="user",
                        max_length=20,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Dotted action key, e.g. 'item.create', 'item.download'.",
                        max_length=100,
                        verbose_name="action",
                    ),
                ),
                (
                    "target_uuid",
                    models.UUIDField(
                        blank=True,
                        help_text="Denormalized target id; survives a hard-deleted target.",
                        null=True,
                        verbose_name="target id",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Denormalized target kind, e.g. 'item', 'itemaccess'.",
                        max_length=50,
                        verbose_name="target type",
                    ),
                ),
                (
                    "path_snapshot",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="ltree path of the target item at the time of the event.",
                        verbose_name="path snapshot",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional structured context for the event.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit event",
                "verbose_name_plural": "Audit events",
                "db_table": "drive_audit_event",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="item",
            name="content_type",
            field=models.CharField(
                blank=True,
                help_text="Content object type key (ADR-0001); NULL for a plain file/folder.",
                max_length=50,
                null=True,
                verbose_name="content type",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Business metadata as a JSON object (classable, GIN-indexed).",
                validators=[core.models.validate_metadata_object],
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["metadata"], name="drive_item_metadata_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["content_type"], name="drive_item_content_type_idx"),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                help_text="User behind the action; NULL for system/anonymous actors.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="actor",
            ),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="target",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_events",
                to="core.item",
                verbose_name="target item",
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(fields=["target_uuid"], name="drive_audit_target_idx"),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(fields=["actor", "-created_at"], name="drive_audit_actor_idx"),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(fields=["action", "-created_at"], name="drive_audit_action_idx"),
        ),
    ]
